apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "finops-composition-definition-parser.fullname" . }}
  labels:
    {{- include "finops-composition-definition-parser.labels" . | nindent 4 }}
rules:
- apiGroups: ["core.krateo.io"]
  resources: ["compositiondefinitions"]
  verbs: ["get", "list"]