apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-composition-definition-parser.fullname" . }}
  labels:
  {{- include "finops-composition-definition-parser.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 
  PORT_FINOPS_COMPOSITION_DEFINITION_PARSER: "{{ .Values.service.port }}"